auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: shawn0lee0博客
url: http://shawn0lee0.github.io/
feed: /atom.xml
author_info: <a href="http://shawn0lee0.github.io/">robo_one</a>
